name: Build, Test, Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    services: 
      mysqldb:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 12
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15.0
      - name: before-install
        run: |
          node --version
          npm --version
          go version
      - name: install-deps
        run: |
          npm ci
          go mod download
      - name: start-database
        run: |
          mysql --host mysqldb -uroot -ppassword -e "CREATE USER adb_user@localhost IDENTIFIED BY 'adbpassword';"
          mysql --host mysqldb -uroot -ppassword -e "GRANT ALL PRIVILEGES ON *.* to adb_user@localhost;"
          mysql --host mysqldb -uroot -ppassword -e "CREATE DATABASE adb_db CHARACTER SET utf8 COLLATE utf8_general_ci;"
          mysql --host mysqldb -uroot -ppassword -e "CREATE DATABASE adb_test_db CHARACTER SET utf8 COLLATE utf8_general_ci;"
      - name: test
        run: |
          ./hooks/pre-commit
          go test github.com/dxe/adb/...
#       - uses: kciter/aws-ecr-action@master
#         with:
#           access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           account_id: ${{ secrets.AWS_ACCOUNT_ID }}
#           repo: docker/repo
#           region: ap-northeast-2
#           tags: latest,${{ github.sha }}
#           create_repo: true
    
